### ISSUE TITLE
avr-size reports higher size of hex files generated by ubirch-avr

### ISSUE THREAD

**Issue by amitesh-singh** [ubirch/ubirch-avr#1]
IF you compare the same program built by ubirch-avr and arduino ide, avr-size reports higher size of hex files generated by ubirch-avr.

**Comment by thinkberg** [comment]
That is entirely possible. The compiler and linker flags are probably not the same. Are both compiled with debug?

**Comment by amitesh-singh** [comment]
This is the program:
https://github.com/amitesh-singh/amiduino/blob/master/avr/ami-arduino-cmake/sketches/esp8266-thingspeak-temp-plot-no-lcd/thingspeak.cpp

AVR gcc version: avr-gcc --version
avr-gcc (GCC) 4.8.1

Platform: Ubuntu 15.10

There is a significant change in size
Arduino ide: 25% of 32kb
cmake: 53.3% of 32 kb

build log with cmake:
http://pastebin.com/zJR8qV1s

build log with arduino ide:
http://pastebin.com/dmVY5Yp1

**Comment by amitesh-singh** [comment]
ah, it is False Alarm: it was my fault to comment the flags for binary.
#set(CMAKE_EXE_LINKER_FLAGS "-Wl,--relax -Wl,--gc-sections -Wl,-u,vfscanf -lscanf_min -Wl,-u,vfprintf -lprintf_min ${EXTRA_LIBS}" CACHE STRING "")

although printf and other libs were eating few kbs. my mistake was to comment out above line.
Now, I added set(CMAKE_EXE_LINKER_FLAGS "-Wl,--relax -Wl,--gc-sections which saves more bytes (better than arduino ide since it does not use -Wl,--relax).

**Comment by amitesh-singh** [comment]
Ok, I asked few people on #avr why Arduino IDE does not use -Wl,--relax, They say, it is not guaranteed to work all the time. I check the results with -Wl,--relax once.

**Comment by thinkberg** [comment]
It is usually more of a hint, so it should not be a problem.

**Comment by amitesh-singh** [comment]
btw, thanks for writing this project. I love it. :+1: 
I don't like Arduino IDE much.
